// Per-game asset codegen: turn the asset index (+ optional atlas map) into a
// single generated TypeScript module the game imports — a typed asset manifest,
// optional atlas frame table, animation bindings, and a thin, framework-agnostic
// (DOM-only, no engine import) loader. Pure: takes data, returns the module text.

import type { AssetIndex } from "./asset-index.ts";

/** Loose shape of a `<game>.atlas.json` produced by `assetgen atlas`. */
export interface AtlasMapJson {
  pages: Array<{ image: string; width: number; height: number }>;
  frames: Array<{ id: string; page: number; x: number; y: number; w: number; h: number }>;
}

/** Drop the file extension so ids are stable, readable keys. */
export function assetId(path: string): string {
  return path.replace(/\.[^.]+$/, "");
}

/**
 * Map each path to a unique id: the extension-stripped id, except where that
 * would collide (e.g. `x.png` + `x.webp`), in which case the colliding paths
 * keep their extension so no asset is silently dropped from the manifest.
 */
export function buildIdMap(paths: string[]): Map<string, string> {
  const counts = new Map<string, number>();
  for (const p of paths) counts.set(assetId(p), (counts.get(assetId(p)) ?? 0) + 1);
  const ids = new Map<string, string>();
  for (const p of paths) {
    const clean = assetId(p);
    ids.set(p, (counts.get(clean) ?? 0) > 1 ? p : clean);
  }
  return ids;
}

const DEFAULT_FPS = 12;

export function buildCodegenModule(index: AssetIndex, atlas: AtlasMapJson | null, game: string): string {
  const images = index.assets.filter((a) => a.type === "image");
  const idOf = buildIdMap(images.map((a) => a.path));
  const id = (path: string): string => idOf.get(path) ?? assetId(path);
  const out: string[] = [];

  out.push(`// GENERATED by \`assetgen codegen --game ${game}\` — do not edit by hand.`);
  out.push(`// Typed asset manifest + thin DOM loader for "${game}". Framework-agnostic:`);
  out.push(`// plain data, no engine import. Regenerate after changing assets.`);
  out.push("");

  out.push("export const ASSETS = {");
  for (const a of images) {
    const frames = a.type === "image" ? (a.sheet?.frames ?? 1) : 1;
    out.push(
      `  ${JSON.stringify(id(a.path))}: { path: ${JSON.stringify(a.path)}, width: ${a.width}, height: ${a.height}, frames: ${frames} },`,
    );
  }
  out.push("} as const;");
  out.push("");
  out.push("export type AssetId = keyof typeof ASSETS;");
  out.push("export interface AssetMeta { path: string; width: number; height: number; frames: number }");
  out.push("");

  if (atlas) {
    out.push("export const ATLAS = {");
    out.push(`  pages: ${JSON.stringify(atlas.pages)} as ReadonlyArray<{ image: string; width: number; height: number }>,`);
    out.push("  frames: {");
    for (const f of [...atlas.frames].sort((a, b) => a.id.localeCompare(b.id))) {
      out.push(`    ${JSON.stringify(id(f.id))}: { page: ${f.page}, x: ${f.x}, y: ${f.y}, w: ${f.w}, h: ${f.h} },`);
    }
    out.push("  },");
    out.push("} as const;");
    out.push("");
  }

  const sheets = images.filter((a) => a.type === "image" && (a.sheet?.frames ?? 1) > 1);
  out.push("// Animation clips derived from sprite-sheet metadata (run `assetgen index --frame-size`");
  out.push("// to populate frame grids). fps defaults to 12; tune per clip as needed.");
  out.push("export const ANIMATIONS = {");
  for (const a of sheets) {
    if (a.type !== "image" || !a.sheet) continue;
    out.push(
      `  ${JSON.stringify(id(a.path))}: { frameWidth: ${a.sheet.frameWidth}, frameHeight: ${a.sheet.frameHeight}, frames: ${a.sheet.frames}, fps: ${DEFAULT_FPS}, loop: true },`,
    );
  }
  out.push("} as const;");
  out.push("");
  out.push("export type AnimationId = keyof typeof ANIMATIONS;");
  out.push("");

  out.push("/** Preload every asset as an HTMLImageElement, keyed by id. Browser-only. */");
  out.push("export async function loadAssets(base = \"/assets/\"): Promise<Record<AssetId, HTMLImageElement>> {");
  out.push("  const ids = Object.keys(ASSETS) as AssetId[];");
  out.push("  const loaded = await Promise.all(");
  out.push("    ids.map(");
  out.push("      (id) =>");
  out.push("        new Promise<[AssetId, HTMLImageElement]>((resolve, reject) => {");
  out.push("          const img = new Image();");
  out.push("          img.onload = () => resolve([id, img]);");
  out.push("          img.onerror = () => reject(new Error(`failed to load ${ASSETS[id].path}`));");
  out.push("          img.src = base + ASSETS[id].path;");
  out.push("        }),");
  out.push("    ),");
  out.push("  );");
  out.push("  return Object.fromEntries(loaded) as Record<AssetId, HTMLImageElement>;");
  out.push("}");
  out.push("");

  return out.join("\n");
}
